(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by LiveScript 1.4.0
module.exports = {
  fn: function(it){
    return it + 4;
  }
};


},{}],2:[function(require,module,exports){
// Generated by LiveScript 1.4.0
var depend, fn;
depend = require('./depend.ls');
fn = function(){
  return depend.fn(6);
};


},{"./depend.ls":1}]},{},[2])
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIm5vZGVfbW9kdWxlcy9icm93c2VyLXBhY2svX3ByZWx1ZGUuanMiLCIvaG9tZS9iYXJhbmRpcy9kZXYvcHJvamVjdHMvbHNpZnkvdGVzdC90ZXN0cy9tYXAvZGVwZW5kLmxzIiwiL2hvbWUvYmFyYW5kaXMvZGV2L3Byb2plY3RzL2xzaWZ5L3Rlc3QvdGVzdHMvbWFwL2lucHV0LmxzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBOztBQ0FBLE1BQU0sQ0FBQyxPQUFRLENBQUEsQ0FBQSxDQUNiO0VBQUEsSUFBSSxRQUFBLENBQUEsRUFBQTtXQUFHLEVBQUcsQ0FBQSxDQUFBLENBQUU7O0FBQVo7Ozs7OztBQ0RPLE1BQUEsQ0FBQSxDQUFBLENBQUEsT0FBQSxDQUFBLGFBQUE7QUFFVCxFQUFHLENBQUEsQ0FBQSxDQUFFLFFBQUEsQ0FBQTtTQUFHLE1BQU0sQ0FBQyxHQUFHLENBQUEiLCJmaWxlIjoiZ2VuZXJhdGVkLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXNDb250ZW50IjpbIihmdW5jdGlvbiBlKHQsbixyKXtmdW5jdGlvbiBzKG8sdSl7aWYoIW5bb10pe2lmKCF0W29dKXt2YXIgYT10eXBlb2YgcmVxdWlyZT09XCJmdW5jdGlvblwiJiZyZXF1aXJlO2lmKCF1JiZhKXJldHVybiBhKG8sITApO2lmKGkpcmV0dXJuIGkobywhMCk7dmFyIGY9bmV3IEVycm9yKFwiQ2Fubm90IGZpbmQgbW9kdWxlICdcIitvK1wiJ1wiKTt0aHJvdyBmLmNvZGU9XCJNT0RVTEVfTk9UX0ZPVU5EXCIsZn12YXIgbD1uW29dPXtleHBvcnRzOnt9fTt0W29dWzBdLmNhbGwobC5leHBvcnRzLGZ1bmN0aW9uKGUpe3ZhciBuPXRbb11bMV1bZV07cmV0dXJuIHMobj9uOmUpfSxsLGwuZXhwb3J0cyxlLHQsbixyKX1yZXR1cm4gbltvXS5leHBvcnRzfXZhciBpPXR5cGVvZiByZXF1aXJlPT1cImZ1bmN0aW9uXCImJnJlcXVpcmU7Zm9yKHZhciBvPTA7bzxyLmxlbmd0aDtvKyspcyhyW29dKTtyZXR1cm4gc30pIiwibW9kdWxlLmV4cG9ydHMgPVxuICBmbjogLT4gaXQgKyA0XG4iLCJyZXF1aXJlISAnLi9kZXBlbmQubHMnXG5cbmZuID0gLT4gZGVwZW5kLmZuIDZcbiJdfQ==
